# Generated by Django 3.2.3 on 2021-05-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('grad_year', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
            ],
        ),
    ]
