# Generated by Django 3.2.3 on 2021-05-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_user_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_forgot_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
