# Generated by Django 3.2.3 on 2021-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_user_forgot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_forgot_password',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
