# Generated by Django 3.2.3 on 2021-05-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rejection', '0002_rejection_reasons_db_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejection_reasons_db',
            old_name='question',
            new_name='reason',
        ),
    ]
