# Generated by Django 3.2.3 on 2021-05-28 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='general_questions_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_of_upload', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='answers_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('time_of_upload', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='q_and_a.general_questions_db')),
            ],
        ),
    ]
